# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{im_isbn}
  s.version = File.open("VERSION").read.strip

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["julbouln"]
  s.date = %q{2013-02-10}
  s.default_executable = nil
  s.description = %q{immateriel.fr ISBN lib}
  s.email = %q{jboulnois@immateriel.fr}
  s.executables = []
  s.files = [
    "lib/im_isbn.rb"
  ]
  s.homepage = %q{http://github.com/immateriel/im_isbn}
  s.require_paths = ["lib","data"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{immateriel.fr ISBN lib}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])

    else
      s.add_dependency(%q<nokogiri>, [">= 0"])
    end
  else
    s.add_dependency(%q<nokogiri>, [">= 0"])

  end
end
